### ISSUE TITLE
(no bug) a word of thanks.

### ISSUE THREAD

**Issue by nerd190** [yuvadm/streamlib#15]
Today I found two utilities on Github via the `awesome-rust` list, that are **amazing!**, both made by you!
I found `slingr` first, I now use it via Termux to cast media from my phone or tablet to my Android TV box, I can now uninstall my old casting app and replace it with `slingr` instead, bye (interpreted) Java, hello rust!
Then I found this project... **WOW.** 😱 
I much prefer to: stream > download
Over the years I have made both scripts and functions, for `youtube-dl` and `spotdl` (a Spotify client) that allow me to this, keep organised lists to stream with `mpv` (instead of downloading anything)
Its hassle though, as these clients are designed to **download**, but *can* **stream**, this is designed purely to organise **streaming** (no focus on downloading), now all I have to do is collect my URLs and add them to a library, **Thank you!**
I will add a playlist to the library repo, I use it when I cant be bothered to search for anything and just want some chilled music to code with (LoFi HipHop beats).
Let me close this "issue" now 🤣

**Comment by yuvadm** [comment]
@5c0tt-b0t that's really great to hear that you're finding these utilities useful! :smile_cat: 

I know for a fact that some maintenance and changes are required to get things working, especially in Slingr. Feel free to push any changes you have upstream, I'll happily merge any PRs.

Cheers! :tada:
